##web application
web:
 build: ./webcontainer
 
 ports:
  - "80:80"
 depends_on:
  - db     
  - php

##php container
  php:
   build ./php.container
  ports:
   - "9000:9000"

##mysql container
 db:
  build ./mysql_container
  ports:
  - "3306:3306"
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: userpass
    MYSQL_DATABASE: root_test
