web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./webcontainer/code:/code
        - ./webcontainer/site.conf:/etc/nginx/conf.d/site.conf

    links:
        - php
        - db


php:
#    image: php:7-fpm
    build: ./php_container
    volumes:
        - ./webcontainer/code:/code
    links:
        - db
db:
#    image: mysql
  build: ./mysql_container
   # context: ./mysql_container

  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
#    volumes:
#      - ./mysql_container/employees.sql:/docker-entrypoint-initdb.d

